version: '3.9'
services:
  api:
    build: ./backend
    command: uvicorn edge-terminal.backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  web:
    build: ./frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - api
